#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using the while loop

counter=1

while [ $counter -le 10 ]; do
    echo "Best School"
    # Increment the counter
    ((counter++))
done

exit 0
